version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ACCOUNT_ID: 521886307975
    IMAGE_REPO_NAME: santhiya/brain-tasks-app
    IMAGE_TAG: latest

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e3g4s9r7
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name brain-cluster

  build:
    commands:
      - echo Build started on `date`
      - docker build -t santhiya/brain-task .
      - docker tag santhiya/brain-task:latest public.ecr.aws/e3g4s9r7/santhiya/brain-task:latest

  post_build:
    commands:
      - echo Pushing image to ECR
      - docker push public.ecr.aws/e3g4s9r7/santhiya/brain-task:latest
      - echo Deploying to EKS
