apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: codebuild-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codebuild-deployer-binding
  namespace: default
subjects:
- kind: User
  name: arn:aws:iam::521886307975:role/Myrole
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: codebuild-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codebuild-cluster-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codebuild-cluster-reader-binding
subjects:
- kind: User
  name: arn:aws:iam::521886307975:role/Myrole
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: codebuild-cluster-reader
  apiGroup: rbac.authorization.k8s.io

